title: kazemi.dev
description: kazemi.dev
url: "https://kazemi.dev"
baseurl: ""  # No trailing slash
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache  

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true
